name: bcftools_stats
description: Generates stats from VCF files
keywords:
    - variant calling
    - stats
    - VCF
tools:
    - stats:
        description: |
          Parses VCF or BCF and produces text file stats which is suitable for
          machine processing and can be plotted using plot-vcfstats.
        homepage: http://samtools.github.io/bcftools/bcftools.html
        documentation: http://www.htslib.org/doc/bcftools.html
        doi: 10.1093/bioinformatics/btp352
params:
    - outdir:
        type: string
        description: |
          The pipeline's output directory. By default, the module will
          output files into `$params.outdir/<SOFTWARE>`
    - publish_dir_mode:
        type: string
        description: |
          Value for the Nextflow `publishDir` mode parameter.
          Available: symlink, rellink, link, copy, copyNoFollow, move.
    - enable_conda:
        type: boolean
        description: |
          Run the module with Conda using the software specified
          via the `conda` directive
    - singularity_pull_docker_container:
        type: boolean
        description: |
          Instead of directly downloading Singularity images for use with Singularity,
          force the workflow to pull and convert Docker containers instead.
input:
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - vcf:
        type: file
        description: VCF input file
        pattern: "*.{vcf}"
output:
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - stats:
        type: file
        description: Text output file containing stats
        pattern: "*.{txt}"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@joseespinosa"
    - "@drpatelh"
