name: bedtools_complement
description: Returns all intervals in a genome that are not covered by at least one interval in the input BED/GFF/VCF file.
keywords:
    - bed
    - complement
tools:
    - bedtools:
        description: |
            A set of tools for genomic analysis tasks, specifically enabling genome arithmetic (merge, count, complement) on various file types.
        documentation: https://bedtools.readthedocs.io/en/latest/content/tools/complement.html
params:
    - outdir:
        type: string
        description: |
            The pipeline's output directory. By default, the module will
            output files into `$params.outdir/<SOFTWARE>`
    - publish_dir_mode:
        type: string
        description: |
            Value for the Nextflow `publishDir` mode parameter.
            Available: symlink, rellink, link, copy, copyNoFollow, move.
    - enable_conda:
        type: boolean
        description: |
            Run the module with Conda using the software specified
            via the `conda` directive
    - singularity_pull_docker_container:
        type: boolean
        description: |
            Instead of directly downloading Singularity images for use with Singularity,
            force the workflow to pull and convert Docker containers instead.
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - bed:
        type: file
        description: Input BED file
        pattern: "*.{bed}"
    - sizes:
        type: file
        description: File which defines the chromosome lengths for a given genome
        pattern: "*.{sizes}"
output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - bed:
        type: file
        description: Bed file with all genomic intervals that are not covered by at least one record from the input file.
        pattern: "*.{bed}"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@Emiller88"
    - "@sruthipsuresh"
    - "@drpatelh"
