name: quast
description: Quality Assessment Tool for Genome Assemblies
keywords:
  - quast
  - assembly
  - quality
tools:
  - quast:
      description: |
        QUAST calculates quality metrics for genome assemblies
      homepage: http://bioinf.spbau.ru/quast
      doi:
params:
  - outdir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$params.outdir/<SOFTWARE>`
  - publish_dir_mode:
      type: string
      description: |
        Value for the Nextflow `publishDir` mode parameter.
        Available: symlink, rellink, link, copy, copyNoFollow, move.
  - enable_conda:
      type: boolean
      description: |
        Run the module with Conda using the software specified
        via the `conda` directive
  - singularity_pull_docker_container:
      type: boolean
      description: |
        Instead of directly downloading Singularity images for use with Singularity,
        force the workflow to pull and convert Docker containers instead.

input:
  - consensus:
      type: file
      description: |
        Fasta file containing the assembly of interest
  - fasta:
      type: file
      description: |
        The genome assembly to be evaluated. Has to contain at least a non-empty string dummy value.
  - use_fasta:
      type: boolean
      description: Whether to use the provided fasta reference genome file
  - gff:
      type: file
      description: The genome GFF file. Has to contain at least a non-empty string dummy value.
  - use_gff:
      type: boolean
      description: Whether to use the provided gff reference annotation file

output:
  - quast:
      type: directory
      description: Directory containing complete quast report
      pattern: "{prefix}.lineage_report.csv"
  - report:

  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

authors:
  - "@drpatelh"
  - "@kevinmenden"
