name: seacr_callpeak
description: Call peaks using SEACR on sequenced reads in bedgraph format
keywords:
    - peak-caller
    - peaks
    - bedgraph
    - cut&tag
    - cut&run
    - chromatin
    - seacr
tools:
    - seacr:
        description: |
            SEACR is intended to call peaks and enriched regions from sparse CUT&RUN
            or chromatin profiling data in which background is dominated by "zeroes"
            (i.e. regions with no read coverage).
        homepage: https://github.com/FredHutch/SEACR
        documentation: https://github.com/FredHutch/SEACR
params:
    - outdir:
        type: string
        description: |
            The pipeline's output directory. By default, the module will
            output files into `$params.outdir/<SOFTWARE>`
    - publish_dir_mode:
        type: string
        description: |
            Value for the Nextflow `publishDir` mode parameter.
            Available: symlink, rellink, link, copy, copyNoFollow, move.
    - enable_conda:
        type: boolean
        description: |
            Run the module with Conda using the software specified
            via the `conda` directive
    - singularity_pull_docker_container:
        type: boolean
        description: |
            Instead of directly downloading Singularity images for use with Singularity,
            force the workflow to pull and convert Docker containers instead.
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - bedgraph:
        type: file
        description: |
            The target bedgraph file from which the peaks will be calculated.
    - ctrlbedgraph:
        type: file
        description: |
            Control (IgG) data bedgraph file to generate an empirical threshold for peak calling.
output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - bed:
        type: file
        description: Bed file containing the calculated peaks.
        pattern: "*.bed"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@chris-cheshire"
