name: minimap2_align
description: A versatile pairwise aligner for genomic and spliced nucleotide sequences
keywords:
    - align
    - fasta
    - fastq
    - genome
    - paf
    - reference
tools:
    - minimap2:
        description: |
            A versatile pairwise aligner for genomic and spliced nucleotide sequences.
        homepage: https://github.com/lh3/minimap2
        documentation: https://github.com/lh3/minimap2#uguide
params:
    - outdir:
        type: string
        description: |
            The pipeline's output directory. By default, the module will
            output files into `$params.outdir/<SOFTWARE>`
    - publish_dir_mode:
        type: string
        description: |
            Value for the Nextflow `publishDir` mode parameter.
            Available: symlink, rellink, link, copy, copyNoFollow, move.
    - enable_conda:
        type: boolean
        description: |
            Run the module with Conda using the software specified
            via the `conda` directive
    - singularity_pull_docker_container:
        type: boolean
        description: |
            Instead of directly downloading Singularity images for use with Singularity,
            force the workflow to pull and convert Docker containers instead.
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
            List of input FASTA or FASTQ files of size 1 and 2 for single-end
            and paired-end data, respectively.
    - reference:
        type: file
        description: |
            Reference database in FASTA format.
output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - paf:
        type: file
        description: Alignment in PAF format
        pattern: "*.paf"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@heuermh"
