name: star_genomegenerate
description: Create index for STAR
keywords:
  - index
  - fasta
  - genome
  - reference
tools:
  - star:
      description: |
        STAR is a software package for mapping DNA sequences against
        a large reference genome, such as the human genome.
      homepage: https://github.com/alexdobin/STAR
      manual: https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf
      doi: 10.1093/bioinformatics/bts635
params:
  - outdir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$params.outdir/<SOFTWARE>`
  - publish_dir_mode:
      type: string
      description: |
        Value for the Nextflow `publishDir` mode parameter.
        Available: symlink, rellink, link, copy, copyNoFollow, move.
  - enable_conda:
      type: boolean
      description: |
        Run the module with Conda using the software specified
        via the `conda` directive
  - singularity_pull_docker_container:
      type: boolean
      description: |
        Instead of directly downloading Singularity images for use with Singularity,
        force the workflow to pull and convert Docker containers instead.

input:
  - fasta:
      type: file
      description: Fasta file of the reference genome
  - gtf:
      type: file
      description: GTF file of the reference genome

output:
  - index:
      type: directory
      description: Folder containing the star index files
      pattern: "star"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

authors:
  - "@kevinmenden"
  - "@drpatelh"
