name: dsh_splitbed
description: Split features in gzipped BED format
keywords:
    - bed
tools:
    - dsh:
        description: |
            Reads, features, variants, assemblies, alignments, genomic range trees, pangenome
            graphs, and a bunch of random command line tools for bioinformatics. LGPL version 3
            or later.
        homepage: https://github.com/heuermh/dishevelled-bio
        documentation: https://github.com/heuermh/dishevelled-bio
params:
    - outdir:
        type: string
        description: |
            The pipeline's output directory. By default, the module will
            output files into `$params.outdir/<SOFTWARE>`
    - publish_dir_mode:
        type: string
        description: |
            Value for the Nextflow `publishDir` mode parameter.
            Available: symlink, rellink, link, copy, copyNoFollow, move.
    - enable_conda:
        type: boolean
        description: |
            Run the module with Conda using the software specified
            via the `conda` directive
    - singularity_pull_docker_container:
        type: boolean
        description: |
            Instead of directly downloading Singularity images for use with Singularity,
            force the workflow to pull and convert Docker containers instead.
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - bed:
        type: file
        description: Features in gzipped BED format to split
        pattern: "*.{bed.gz}"
output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - bed:
        type: file
        description: Features in split gzipped BED formatted files
        pattern: "*.{bed.gz}"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@heuermh"
